In [10]:
import numpy as np

In [11]:
#this help you to download the file over the
#internet and store the file in you local code enviroment
import urllib.request
file_id = "1W0geEaa6JK7XOtJFfnUhNCsUalu_xYFQ"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
request = urllib.request.urlretrieve(url,"student.csv")
print(request)


('student.csv', <http.client.HTTPMessage object at 0x786dbf6060f0>)


In [12]:
#np.genfromtxt :- genfromtxt() is one of the most important
# NumPy functions for loading student_data from text files and CSV files.

In [13]:
student_data = np.genfromtxt("student.csv" , delimiter ="," , dtype= int , skip_header= 1)
print(student_data)

[[ 7 56  8  7 10 62]
 [ 4 69  5  3  8 56]
 [11 60  7  6 10 45]
 ...
 [10 44  8  5 10 37]
 [10 75  7  5  8 52]
 [ 2 70  6 11 16 52]]


In [14]:
print(student_data.shape)

(10000, 6)


In [15]:
line1= student_data[0:1]
line1
for i in line1:
  print(i)

[ 7 56  8  7 10 62]


In [16]:
weather = [ 2.0 , 3.0, 4.4, 1.2, 3.4 , 5.5]

In [17]:
#matrix multiplication in numpy
answer = line1 @ weather
answer

array([600.6])

In [18]:
#another way of matrix multiplication
ans = np.matmul(line1, weather)
ans


array([600.6])

In [19]:
#.dot function in  in numpy
ans1 = np.dot(line1 , weather)
ans1

array([600.6])

In [20]:
ans2 = np.dot(student_data , weather)
ans2

array([600.6, 575.8, 521.5, ..., 430.7, 595. , 594. ])

In [21]:
ans3 =student_data @ weather
ans3

array([600.6, 575.8, 521.5, ..., 430.7, 595. , 594. ])

In [22]:
student_data.shape

(10000, 6)

In [23]:
#how to add a line in  yur existing student_data
#how to add a column in you estudent_dataing student_data
#npstudent_dataatenate
new_student_data = np.concatenate((student_data, ans3.reshape(10000, 1)), axis= 1)
#student_data = The Existing data That we have
#ans3 = is the newly created column that we created & want to Insert
#.reshape = help to reshae tyhe vector data into column format
#(10000, 1) =  it used iwth respae and concatenate both that tells the ans is 10000 rows and
  # 1 = means that in the student_data we used to inert t from the row no 1 co  row no is 0 is a header
                            # inrrer calcultion student_data (10000 ,0)  + Ans3 (1000, 1)
                            #finally the row were added and b nvbi
nsd = new_student_data
nsd

array([[  7. ,  56. ,   8. , ...,  10. ,  62. , 600.6],
       [  4. ,  69. ,   5. , ...,   8. ,  56. , 575.8],
       [ 11. ,  60. ,   7. , ...,  10. ,  45. , 521.5],
       ...,
       [ 10. ,  44. ,   8. , ...,  10. ,  37. , 430.7],
       [ 10. ,  75. ,   7. , ...,   8. ,  52. , 595. ],
       [  2. ,  70. ,   6. , ...,  16. ,  52. , 594. ]])

In [24]:
#np.savetxt() is used to save a NumPy array to a text file (.txt, .csv, etc.).
np.savetxt(
    "student_data_updated.csv",
    nsd,
    delimiter = ', ' ,
    fmt = '%.2f',
    header = " cl1 , cl2,cl3,cl4,cl5,cl6"
)

In [25]:
nsd.dtype

dtype('float64')

In [26]:
student_data.dtype

dtype('int64')

In [27]:
print(type(nsd))

<class 'numpy.ndarray'>


Random Function

In [28]:
#ceating a random array just for some calculation
array1 = np.random.rand(3, 4)
#array = np.random.rand(no_of_rows  , no_of_column )
#np.random.rand creates a array of random floating points between 0 and 1
#3 means 3 rows
#4 means = 4 columns
array1
array1.ndim

2

Random Fuction With Uniform

In [29]:
#Random Function :- helps to to create random array
   #Sub Fuction :.uniformHelps to crte the random array between 2 numbers
Random_array = np.random.uniform(10,90, (3,4))
# its created a random array and
#.uniform create a array a between 2 numbers
#.unform(starting_point , Ending_point , (no_of_rows , no_of_columns))
Random_array
"""Problem :- Now We can see there are so many demials"""


'Problem :- Now We can see there are so many demials'

Round Of Function

In [30]:
#np.round = its help to round of the figgures
round_of = np.round(Random_array, 2)
roud_of_ = np.round(Random_array)

# round_of
roud_of_

array([[73., 36., 45., 87.],
       [68., 34., 23., 30.],
       [80., 37., 79., 18.]])

## ***ARITHMATICS OPRATIONS ***

In [31]:
# Arithmatic operations
array1 = np.round(np.random.uniform(10, 40, (4, 3)), 2)
array2 = np.round(np.random.uniform(10,40, (4,3)),2)
array1

array([[19.63, 38.92, 20.58],
       [19.28, 28.61, 37.62],
       [19.35, 14.45, 33.8 ],
       [28.51, 17.24, 22.74]])

In [32]:
array2

array([[36.66, 23.24, 23.54],
       [11.75, 34.42, 38.2 ],
       [23.53, 25.7 , 39.41],
       [34.37, 39.1 , 12.91]])

In [33]:
sum = array1 + array2
sum

array([[56.29, 62.16, 44.12],
       [31.03, 63.03, 75.82],
       [42.88, 40.15, 73.21],
       [62.88, 56.34, 35.65]])

In [34]:
minus = array1 - array2
minus

array([[-17.03,  15.68,  -2.96],
       [  7.53,  -5.81,  -0.58],
       [ -4.18, -11.25,  -5.61],
       [ -5.86, -21.86,   9.83]])

In [35]:
multiply = array1 * array2
multiply

array([[ 719.6358,  904.5008,  484.4532],
       [ 226.54  ,  984.7562, 1437.084 ],
       [ 455.3055,  371.365 , 1332.058 ],
       [ 979.8887,  674.084 ,  293.5734]])

In [36]:
divide = array1 / array2
divide

array([[0.53546099, 1.6746988 , 0.87425658],
       [1.64085106, 0.83120279, 0.98481675],
       [0.82235444, 0.56225681, 0.85765034],
       [0.82950247, 0.44092072, 1.76142525]])

In [37]:
sum_w_3 = array1 + 3
sum_w_3

array([[22.63, 41.92, 23.58],
       [22.28, 31.61, 40.62],
       [22.35, 17.45, 36.8 ],
       [31.51, 20.24, 25.74]])

In [38]:
multiply = array1 * 3
multiply

array([[ 58.89, 116.76,  61.74],
       [ 57.84,  85.83, 112.86],
       [ 58.05,  43.35, 101.4 ],
       [ 85.53,  51.72,  68.22]])

In [39]:
divide = np.round(array1 /3)
divide

array([[ 7., 13.,  7.],
       [ 6., 10., 13.],
       [ 6.,  5., 11.],
       [10.,  6.,  8.]])

In [40]:
reminder = array1 % 2
reminder

array([[1.63, 0.92, 0.58],
       [1.28, 0.61, 1.62],
       [1.35, 0.45, 1.8 ],
       [0.51, 1.24, 0.74]])

Brodcasting

In [41]:
#broadcasting only works if the shape of the
# array is match otherwise its dont works

Smaller array
      ↓
NumPy stretches it
      ↓
Shapes become compatible
      ↓
Operation happens element-wise

In [42]:
array1 =np.round( np.random.uniform(10, 30,(3,2)))
array1

array([[28., 12.],
       [29., 24.],
       [24., 14.]])

In [43]:
array2 = np.round(np.random.uniform(10,30,(2,3)))
array3 = np.round(np.random.uniform(5, 10 ,(3,2)),2)
array2
array3

array([[7.64, 5.55],
       [6.19, 7.21],
       [6.  , 5.81]])

In [44]:
brodcasting = array1+ array3
brodcasting
#This Work Because array1 & array3 have same shape
# array1+array2 # this is not going to work because there shape should not be same

array([[35.64, 17.55],
       [35.19, 31.21],
       [30.  , 19.81]])

In [45]:
array4 = np.round(np.random.uniform(10, 20 ,(1,1)))
array4

brdcst_result = array1 +array4
brdcst_result
#this is going to work beacuse array4 is brodcasred and mergege with array1


array([[48., 32.],
       [49., 44.],
       [44., 34.]])

**Comparison Operators**

In [46]:
array1

array([[28., 12.],
       [29., 24.],
       [24., 14.]])

In [47]:
array3

array([[7.64, 5.55],
       [6.19, 7.21],
       [6.  , 5.81]])

In [48]:
#Rule:- For compare beetween 2 array the length of the both
#array should be same othewise the comparesion dosent work
compare = array1 == array3
compare
#not a singe values is same  so its returns tthe bolean array

array([[False, False],
       [False, False],
       [False, False]])

In [49]:
#comapred beetween 2 array   using the less then and equal to
compare1 = array1 <= array3
compare1

array([[False, False],
       [False, False],
       [False, False]])

In [50]:
#compared beetween 2 array usingb greated then and equal to
compare2 = array1 >= array3
compare2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [51]:
#compared using the not equal to
compare3 = array1 != array3
compare3

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [52]:
# ARRAY INDEXING AND SCLICING

In [53]:
arr = np.array([
        [[10,30,50,60],
         [88,54,34,32],
         [23,24,25,26]],

        [[20,21,22,23],
         [31,32,33,34],
         [34,35,36,37]],

        [[14,15,16,17],
         [17,18,19,20],
         [23,24,25,26]]

         ])

In [54]:
#get This Output:- [[[20 21 22 23]
  # [31 32 33 34]
  # [34 35 36 37]]]
cool =arr[1:2]
cool
cool.shape

(1, 3, 4)

In [55]:
# #Get This output :-[[60]
#  [23]
#  [17]],
arr[: , 0:1, 3]

array([[60],
       [23],
       [17]])

In [56]:
#Get this output :-  [[20 21 22 23]
#  [31 32 33 34]]
arr[1:2,0:2]

array([[[20, 21, 22, 23],
        [31, 32, 33, 34]]])

In [57]:
arr.shape


(3, 3, 4)

In [58]:
arr[1:2, 0:1,3]

array([[23]])

## Further NumPy Learning Topics

Based on your current knowledge, here are some more advanced and commonly used NumPy features to explore:

*   **Reshaping and Transposing Arrays**: Understanding `np.reshape()`, `np.transpose()`, `.T` attribute, and `np.swapaxes()` to change array dimensions and orientations.
*   **Aggregation Functions**: Learn more about `np.sum()`, `np.mean()`, `np.min()`, `np.max()`, `np.std()`, `np.var()` along specific axes.
*   **Universal Functions (ufuncs)**: Explore more mathematical functions that operate element-wise on arrays, like `np.exp()`, `np.log()`, `np.sqrt()`, trigonometric functions, etc.
*   **Masking and Fancy Indexing**: Using boolean arrays or integer arrays to select subsets of data, which is very powerful for data filtering and manipulation.
*   **Linear Algebra Operations**: Dive deeper into functions for linear algebra such as `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.eig()`, solving linear systems, etc.
*   **Advanced Random Number Generation**: Beyond `np.random.rand()` and `np.random.uniform()`, explore different distributions like `np.random.normal()`, `np.random.randint()`, and understanding the `np.random.Generator` class for better reproducibility.
*   **Saving and Loading Binary NumPy Files**: Learn to use `np.save()` and `np.load()` for efficient storage and retrieval of NumPy arrays in a binary format (`.npy` files).
*   **Sorting**: Understand `np.sort()` and `np.argsort()` for sorting arrays and getting the indices that would sort an array.
*   **Broadcasting Rules**: A deeper understanding of how broadcasting works in more complex scenarios.

These topics will significantly expand your capabilities when working with numerical data in Python using NumPy!

In [59]:
arr =np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [60]:
#transpose
array_transpose =np.transpose(arr)
array_transpose

array([10, 20, 30, 40])

**Other Ways of Creating Numpy array**

In [61]:
creating_array = np.zeros((2,3))
#np.zeros help to cfreate array with zeros and the 2 is indicatining with Row no and
#3 is indicating with column no
#np.zeros((row_number , Column_number))
creating_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.ones((2,3))
#its also work like eros but it create the array with 1 and
#zeros create array with zeros

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
#it create the array with thw one number like 42 or any other no
new_array = np.full([2,3],42)
new_array

array([[42, 42, 42],
       [42, 42, 42]])

In [65]:
#np.arrange (start , end , step )
arrange_arr = np.arange(10 , 20 , 2)
arrange_arr

array([10, 12, 14, 16, 18])

In [73]:
#np.linespace(start ,end , no_of_elemnts_you_want )
np.linspace(10,30, 9).reshape(3,3)
#its created the or find the 9 numbers between 10 and 30
#& created a 2d array using the help og reshape

array([[10. , 12.5, 15. ],
       [17.5, 20. , 22.5],
       [25. , 27.5, 30. ]])